### PR TITLE
Breaks up acvp.c into multiple files

### PR DESCRIPTION
**Pull request by lakshg**
Review

### CODE REVIEW

**Comment by TomMD** [comment]
Muse only responds to PRs from users who have been activated in the private beta.  May I ask how you heard about muse?

**Comment by lakshg** [comment]
> Muse only responds to PRs from users who have been activated in the private beta. May I ask how you heard about muse?

I have already activated beta version

**Comment by lakshg** [comment]
> Muse only responds to PRs from users who have been activated in the private beta. May I ask how you heard about muse?

**Comment by lakshg** [comment]
> Muse only responds to PRs from users who have been activated in the private beta. May I ask how you heard about muse?

Have already have beta version. Could you please guide me how i can view the Muse dev findings

**Comment by TomMD** [comment]
Muse is in a closed beta right now.  Without having been admitted into the beta there will be no analysis performed and no access to results.  You can [sign up to the mailing list](https://muse.dev) to track news of when we open up the product to the general public.

**Comment by TomMD** [comment]
@lakshg I should add that if you're affiliated with an organization working with us already then feel free to reach out over email and we can get things sorted out.

**Pull request closed without merging**
